<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Migration.Net_6_8_BlazorServer.Net_6</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Syncfusion.Blazor" Version="20.3.0.57" />
  </ItemGroup>

</Project>
